# Generated by Django 5.0.6 on 2024-09-07 13:56

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesdb', '0004_remove_product_active_remove_product_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product_images/'),
        ),
    ]
